services:
  health-app:
    image: crpi-aer4k3m8uw2sue3f.cn-hangzhou.personal.cr.aliyuncs.com/dzkdzk/listen-backend:latest
    container_name: listen-spring-app
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - TZ=Asia/Shanghai
      - JAVA_OPTS=-Xms512m -Xmx1g -XX:+UseG1GC
    volumes:
      - ./logs:/app/logs
      # 挂载文件目录：服务器 /usr/local/listen/audio -> 容器 /usr/local/listen/audio
      - /usr/local/listen/audio:/usr/local/listen/audio
      - /usr/local/listen/temp:/usr/local/listen/temp
      - /usr/local/listen/userFile:/usr/local/listen/userFile
