#wx

# AI测试结果评分
aliyun.test-eval.app-id=de56dc3d092e45508bcf316c2525b210
aliyun.test-eval.api-key=sk-c048c72e74024e53a1fe0248b8213f6a
aliyun.test-eval.workspace-id=llm-ycvym6ek3uwuisz0

# AI用户测试分析
aliyun.test-analysis.app-id=b93c807bf05048a0aaa9870bf18cc88c
aliyun.test-analysis.api-key=sk-c048c72e74024e53a1fe0248b8213f6a
aliyun.test-analysis.workspace-id=llm-ycvym6ek3uwuisz0

# AI用户测试结果报告
aliyun.test-report.app-id=b93c807bf05048a0aaa9870bf18cc88c
aliyun.test-report.api-key=sk-c048c72e74024e53a1fe0248b8213f6a
aliyun.test-report.workspace-id=llm-ycvym6ek3uwuisz0

# AI用户阶段分析
aliyun.phase-analysis.app-id=91e77a13aeb24775a116c924adb47acf
aliyun.phase-analysis.api-key=sk-c048c72e74024e53a1fe0248b8213f6a
aliyun.phase-analysis.workspace-id=llm-ycvym6ek3uwuisz0

# AI管理端分析
aliyun.admin-analysis.app-id=64747e1543d143719eafa8e15f321fdb
aliyun.admin-analysis.api-key=sk-c048c72e74024e53a1fe0248b8213f6a
aliyun.admin-analysis.workspace-id=llm-ycvym6ek3uwuisz0
